env:
  matrix:
  - MYCONDAPY=2.7

# Do not use Travis Python to save some time.
language: generic
os:
- linux
- osx
sudo: false

matrix:
  fast_finish: true

cache:
  directories:
  - $HOME/chimera

branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+(\.[0-9]+)?([abc][0-9]*)?$/  # release branches

before_install:
# Get Chimera
- wget https://raw.githubusercontent.com/insilichem/pychimera/master/scripts/install_chimera.sh
- if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
    if [[ ! -e $HOME/chimera/bin/chimera ]]; then
      bash install_chimera.sh;
    fi;
    export CHIMERADIR="$HOME/chimera";
  else
    if [[ ! -e $HOME/chimera/Chimera.app/Contents/Resources/bin/chimera ]]; then
      bash install_chimera.sh;
    fi;
    export CHIMERADIR="$HOME/chimera/Chimera.app/Contents/Resources";
  fi
- rm -rf $CHIMERADIR/lib/python2.7/site-packages/{AutoDockTools,MolKit,PyBabel,mglutil,mmLib,mslib} || true;
# Get miniconda. Take the right version, so re-installing python is hopefully not needed.
- if test -e $HOME/miniconda/bin; then
    echo "miniconda already installed.";
  else
    echo "Installing miniconda.";
    rm -rf $HOME/miniconda;
    mkdir -p $HOME/download;
    if [[ -d $HOME/download/miniconda.sh ]]; then rm -rf $HOME/download/miniconda.sh; fi;
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O $HOME/download/miniconda.sh;
    fi;
    bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
  fi

install:
# Configure conda and get a few essentials
- source $HOME/miniconda/etc/profile.d/conda.sh
- conda activate
- conda config --set always_yes yes
- conda config --remove-key channels || true
- conda config --add channels conda-forge
- conda config --add channels omnia
- conda config --add channels rdkit
- conda config --add channels insilichem
- conda config --add channels insilichem/label/dev
- conda config --add channels defaults
- conda install -q conda conda-build
- conda config --add channels file://$CONDA_PREFIX/conda-bld
# Patch some chimera stuff
- pip install -U numpy==1.12 python-dateutil -t $CHIMERADIR/lib/python2.7/site-packages;
# Show conda info for debugging
- conda info -a
- conda list
- env | sort

script:
- conda build conda-recipe

before_deploy:
- conda install constructor
- constructor installer/
- conda install -q anaconda-client

deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: anaconda -t $ANACONDA_TOKEN upload -u insilichem -l dev $HOME/miniconda/conda-bld/**/tangram*.tar.bz2
    skip_cleanup: true
    on:
      tags: true
      repo: insilichem/tangram
  - provider: releases
    api_key:
      secure: UHkVnHwnj8H48TDhIT2rdi3tfDW82c+6jukO8AyDfx/XYK6cYmyoia3hBLgi3oObkZ+CPt4MYo2drqRFe38jbyYC+ZaKOg/5XlfL7jScmdV1XG1mVQSC6KuV20m0HzI0LSK000xc11czY9yeIiMwOZZaanRLNcfef2oPm0g4uclZiwiqwYSN7yWgMEZprHt1Lo4IKQIMlNzDakSBhhyIjryoKL92UzGWNyW0IJpJY128pNAKIBJ8eAXdOQEduT/E8fkhr9whAGqnnS69PSvS1iNTLh67bXlOUQTsfRXCZowB7N+F8pmw5qfnAoyzssObSjEW9h9taExRpZRZYKJnyk2Urkfk7ED6vUsyCIw8LUi1aj1+08f7elqVBUAWVnmla8Lf/6n+6EF6TIIQKnd8jJp7iRyCK+iaSNcKcPuQ+3MlqDIHWE7WwnAypM5X/WnoDRBsrCjS6l9D+1Pp5m7IZCaGoxVmyKHCBA91SpLVwSLx2E1objjNsSuMEA4SYR/BoJg4rF14es34hTwtaFMBRdWYtyaaCQ7MDoWB9jX4VH/Iu0w+YUHQB21gBFpwEEpvaA0HNdxXhQ9T5sIY0mkwAptBHq1SPhcmjHqjehHnIgZo0YotusUUg2z6O5TZvzZYRMAsfgeBCwCoN+np4D9oPYpQMQuUvzJi0AkqyG326yM=
    file_glob: true
    file: tangram-**.sh
    name: Tangram Suite ${TRAVIS_TAG}
    body: ${TRAVIS_COMMIT_MESSAGE}
    draft: false
    prerelease: false
    skip_cleanup: true
    on:
      tags: true
      repo: insilichem/tangram

after_deploy:
- rm tangram-*.sh